apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-code-with-quarkus-yma3
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhn-gps-stkousso-tenant/my-app/devfile-sample-code-with-quarkus-yma3@sha256:67a58bf0d635a15f1f1ecb897246a8d120d6f9df0066defb4d1357ebc15d57e0
        name: my-java-quarkus
        resources: {}
status: {}
